from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId
from dots_infrastructure.CalculationServiceHelperFunctions import get_single_param_with_name
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions
import numpy as np

from esdl import EnergySystem, EConnection, Building, Battery

from HemsServiceWorkshop.hems_service_workshop_base import HemsServiceWorkshopBase
from HemsServiceWorkshop.hems_service_workshop_dataclasses import OptimizeConsumptionOutput
from pyecore.valuecontainer import EOrderedSet


class HemsServiceWorkshop(HemsServiceWorkshopBase):

    def init_calculation_service(self, energy_system: EnergySystem):
        super().init_calculation_service(energy_system)

    def optimize_consumption(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        ##########
        # INPUTS #
        ##########
        current_reactive_power  = get_single_param_with_name(param_dict, "current_reactive_power")
        current_active_power  = get_single_param_with_name(param_dict, "current_active_power")
        pv_active_power  = get_single_param_with_name(param_dict, "pv_active_power")
        if pv_active_power == None:
            pv_active_power = 0
        max_charge_active_power  = get_single_param_with_name(param_dict, "max_charge_active_power")
        max_discharge_active_power  = get_single_param_with_name(param_dict, "max_discharge_active_power")
        day_ahead_price  = get_single_param_with_name(param_dict, "day_ahead_price")


        # current_active_power: total demand
        # pv_active_power: total power generated by PV

        # def _get_battery(energy_system, esdl_id) -> Battery:
        #     esdl_e_connection: EConnection = EsdlHelperFunctions.get_esdl_object_with_id(energy_system.eAllContents(),
        #                                                                                  esdl_id)
        #     esdl_building: Building = esdl_e_connection.eContainer()
        #     esdl_all_in_building: EOrderedSet = esdl_building.asset
        #
        #     for esdl_obj in esdl_all_in_building:
        #         if isinstance(esdl_obj, Battery):
        #             return esdl_obj

        residual_demand = current_active_power - pv_active_power # >0 = discharge, <0 = charge

        if day_ahead_price is None:
            # self consumption only
            active_power_to_charge = np.clip(-residual_demand, min=max_discharge_active_power, max=max_charge_active_power)
        else:
            if day_ahead_price > 0.05:
                # discharge or self consumption but dont charge
                active_power_to_charge = np.clip(-residual_demand, min=max_discharge_active_power, max=0)
            else:
                # charge but dont discharge
                active_power_to_charge = np.clip(-residual_demand, min=0, max=max_charge_active_power)

        net_active_power = current_active_power + active_power_to_charge - pv_active_power

        aggregated_active_power_1phase = net_active_power / 3
        aggregated_active_power = [aggregated_active_power_1phase, aggregated_active_power_1phase, aggregated_active_power_1phase]

        aggregated_reactive_power_1phase = current_reactive_power / 3
        aggregated_reactive_power = [aggregated_reactive_power_1phase, aggregated_reactive_power_1phase, aggregated_reactive_power_1phase]

        # battery = _get_battery(energy_system, esdl_id)
        # battery_capacity = battery.capacity



        return OptimizeConsumptionOutput(
            aggregated_active_power=aggregated_active_power,
            aggregated_reactive_power=aggregated_reactive_power,
            active_power_to_charge=active_power_to_charge,
        )


if __name__ == "__main__":

    helics_simulation_executor = HemsServiceWorkshop()
    helics_simulation_executor.start_simulation()
    helics_simulation_executor.stop_simulation()