from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem, EConnection
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions

# This file is generated, DO NOT edit this file!

class HemsServiceWorkshopBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()
        self.esdl_obj_mapping : dict[EsdlId, EConnection]= {}

        
        # Calculation: optimize_consumption
        self.optimize_consumption_period_seconds = 900
        optimize_consumption_inputs = [
        
            SubscriptionDescription(esdl_type="ElectricityDemand", 
                                    input_name="current_active_power", 
                                    input_unit="W", 
                                    input_type=h.HelicsDataType.DOUBLE),
            SubscriptionDescription(esdl_type="ElectricityDemand", 
                                    input_name="current_reactive_power", 
                                    input_unit="W", 
                                    input_type=h.HelicsDataType.DOUBLE),
            SubscriptionDescription(esdl_type="PVInstallation", 
                                    input_name="pv_active_power", 
                                    input_unit="W", 
                                    input_type=h.HelicsDataType.DOUBLE),
            SubscriptionDescription(esdl_type="Battery", 
                                    input_name="max_charge_active_power", 
                                    input_unit="W", 
                                    input_type=h.HelicsDataType.DOUBLE),
            SubscriptionDescription(esdl_type="Battery", 
                                    input_name="max_discharge_active_power", 
                                    input_unit="W", 
                                    input_type=h.HelicsDataType.DOUBLE),
            SubscriptionDescription(esdl_type="EnergyMarket", 
                                    input_name="marketPrice", 
                                    input_unit="EUR/MWh", 
                                    input_type=h.HelicsDataType.DOUBLE),
        ]
        optimize_consumption_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="EConnection",
                                    output_name="aggregated_active_power",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.VECTOR),
            PublicationDescription(global_flag=True, 
                                    esdl_type="EConnection",
                                    output_name="aggregated_reactive_power",
                                    output_unit="VAr", 
                                    data_type=h.HelicsDataType.VECTOR),
            PublicationDescription(global_flag=True, 
                                    esdl_type="EConnection",
                                    output_name="active_power_to_charge",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
        ]
        optimize_consumption_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="optimize_consumption", 
            inputs=optimize_consumption_inputs, 
            outputs=optimize_consumption_outputs, 
            calculation_function=self.optimize_consumption
        )
        self.add_calculation(optimize_consumption_information)

    def init_calculation_service(self, energy_system: EnergySystem):
        all_esdl_objs = EsdlHelperFunctions.get_all_esdl_objects_from_type(energy_system.eAllContents(), EConnection)
        for esdl_obj in all_esdl_objs:
            if hasattr(esdl_obj, "id"):
                self.esdl_obj_mapping[esdl_obj.id] = esdl_obj

    
    def optimize_consumption(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    